#!/bin/sh
# Run service-dependent slower integration tests
set -euo xtrace
docker-compose down && docker-compose up -d
export PYTHONPATH=.
export $(cat tests/test.env | xargs)
[ -f .env ] && export $(cat .env | xargs)
poetry run python tests/wait_for_deps.py
poetry run pytest tests/integration
