#!/bin/sh
# Run service-dependent slower integration tests
set -euo xtrace
docker-compose down && docker-compose up -d
docker-compose exec -T app sh -c "PYTHONPATH=/app python -m tests.wait_for_deps && python -m unittest discover /app/tests"
