#!/bin/sh
set -e
set -o xtrace
export PYTHONPATH=.
# Set all env vars
# Load private variables from .env if present
[ -f .env ] && export $(cat .env | xargs)
# Load test variables from tests/test.env
export $(cat tests/test.env | xargs)
# Allow users to set test args
args=${@:-"tests/unit"}
poetry run pytest $args
