#!/bin/sh
set -e
# To be run outside the docker container

scripts/lint

docker-compose down
export PYTHONPATH=.
docker-compose run --rm app sh -c "PYTHONPATH=/app python -m tests.wait_for_deps && python -m unittest discover /app/tests"
