#!/bin/sh
set -euo xtrace
# To be run within the docker container
# This is the entrypoint script for the Dockerfile

docker-compose down -v
docker-compose pull
docker-compose build
docker-compose up app
